{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-spring-boot",
    "version": "1.4.4-2b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.4-2b"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          }
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.4.4-2b.jar",
          "url": "core-spring-boot-1.4.4-2b.jar",
          "size": 18556,
          "sha512": "35144c7008d3789c5226a3485268d9dd1ad010428c4f7b553105e61fa52ce008c30f8cc761df7b53ae2d3fd22124ecc8515a1ddc727dfaac1364f755f36e4a66",
          "sha256": "72263eb804763f7be5b4c61f53286f6f65bc88b78937478bfba94afc54a83269",
          "sha1": "76b6741dd7f687c119a924499c86e03491cff93c",
          "md5": "7e6488252be8609e53710bbfc92c3ceb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.10.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-undertow",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-servlet",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.4-2b"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.4.4-2b.jar",
          "url": "core-spring-boot-1.4.4-2b.jar",
          "size": 18556,
          "sha512": "35144c7008d3789c5226a3485268d9dd1ad010428c4f7b553105e61fa52ce008c30f8cc761df7b53ae2d3fd22124ecc8515a1ddc727dfaac1364f755f36e4a66",
          "sha256": "72263eb804763f7be5b4c61f53286f6f65bc88b78937478bfba94afc54a83269",
          "sha1": "76b6741dd7f687c119a924499c86e03491cff93c",
          "md5": "7e6488252be8609e53710bbfc92c3ceb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-spring-boot-1.4.4-2b-sources.jar",
          "url": "core-spring-boot-1.4.4-2b-sources.jar",
          "size": 11567,
          "sha512": "8b33479a6a2cbed5bc88d8d11b6e734d361d6f97f792c7fca05d4f7fe6c7e5e291e237e517fec536f482520e948fb6a0240e9ebab5bf0634e2c244fd250c47f4",
          "sha256": "eb62b3c53151cea5ec1bbdb5905eabea83bdd38e0115c93d54aea61a64495d81",
          "sha1": "ffd0ce1be10add9e623f1ccb31ce036ce24db1b7",
          "md5": "5dfbfd248012eb40cd69756d948e2837"
        }
      ]
    }
  ]
}
