{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-api",
    "version": "1.4.4-b6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-api-1.4.4-b6.jar",
          "url": "core-api-1.4.4-b6.jar",
          "size": 10642,
          "sha512": "b0cc1fc06fd3d3fd627d78fa96e27d1b7aa037f3f6492d484781b52615d3e1bd21888b6516676a3010bfd74d65b3463691f1a1e389818670aeebcb78188075b6",
          "sha256": "9efd796b98b0e4234ed8acdadcb585284a7f73979652984abc4e6a92fe85370a",
          "sha1": "005d0e776e6e6631c2b742935dca710439915670",
          "md5": "c48aebe52fbd4c209ef0506f6cf5cf16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-api-1.4.4-b6.jar",
          "url": "core-api-1.4.4-b6.jar",
          "size": 10642,
          "sha512": "b0cc1fc06fd3d3fd627d78fa96e27d1b7aa037f3f6492d484781b52615d3e1bd21888b6516676a3010bfd74d65b3463691f1a1e389818670aeebcb78188075b6",
          "sha256": "9efd796b98b0e4234ed8acdadcb585284a7f73979652984abc4e6a92fe85370a",
          "sha1": "005d0e776e6e6631c2b742935dca710439915670",
          "md5": "c48aebe52fbd4c209ef0506f6cf5cf16"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-api-1.4.4-b6-sources.jar",
          "url": "core-api-1.4.4-b6-sources.jar",
          "size": 8479,
          "sha512": "73198d5fb0e22cdc56f5492308c91065418299c937221cac971594a58ddf65ba0ac0ef6ce3d389b4c0ad8814acf6917a1a67944ec3571d4206cec40d5eeb9072",
          "sha256": "9e3095e38d6f7d266068878d0dd3be8a7f9d03fb3e97fce6881b180886831eea",
          "sha1": "27080a6f75eec8bdbf246b78769dd5813d620ebe",
          "md5": "b3ed286771c769e80ff0853c32913c82"
        }
      ]
    }
  ]
}
