{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-spring-boot",
    "version": "1.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          }
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.4.2.jar",
          "url": "core-spring-boot-1.4.2.jar",
          "size": 18551,
          "sha512": "86a005dde00694b42678679990a07e0ab874f29e38f944642a6d1f3d874545bd8c71a5fb276620eafba8272f78d80b3086b12ffee61bac60b4742029ec8d0a65",
          "sha256": "9bc8de693450bfb43f6e5044cc468a316a3f38d8d6110439d17ebd58ece65a2a",
          "sha1": "6f6c74869b91d7fdd2dd7d5790196d0bf2bd470e",
          "md5": "4d1844219fd9a182a1ca45ca8f0bfcbc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.10.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-undertow",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-servlet",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.4.2.jar",
          "url": "core-spring-boot-1.4.2.jar",
          "size": 18551,
          "sha512": "86a005dde00694b42678679990a07e0ab874f29e38f944642a6d1f3d874545bd8c71a5fb276620eafba8272f78d80b3086b12ffee61bac60b4742029ec8d0a65",
          "sha256": "9bc8de693450bfb43f6e5044cc468a316a3f38d8d6110439d17ebd58ece65a2a",
          "sha1": "6f6c74869b91d7fdd2dd7d5790196d0bf2bd470e",
          "md5": "4d1844219fd9a182a1ca45ca8f0bfcbc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-spring-boot-1.4.2-sources.jar",
          "url": "core-spring-boot-1.4.2-sources.jar",
          "size": 11562,
          "sha512": "a9466949ef95985f5c07abf5d69ad87b49c06f4eec50959e1ce1bf1ef1331ff60797d436a75e44b22df0e544b711c6bcf9524742e0c6234425dc239ceb971e36",
          "sha256": "1ccf3de5e13b2edcd30a5641f2c9def60f2185548caf61d6f12eda754a9ddf04",
          "sha1": "554c8484db40850c6f3a347af4f648b0ae0d3252",
          "md5": "cc035485653b708d8897e1c29526464e"
        }
      ]
    }
  ]
}
