{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-spring-boot",
    "version": "1.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          }
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.4.4.jar",
          "url": "core-spring-boot-1.4.4.jar",
          "size": 18554,
          "sha512": "8724da7e5a9e39d8d002db631eabc9b41f7d0e4fd824f85f716bf7a3a3d57859b468068b509d7f59f52229dfd1140a6e8b2102a31787b529d0560914161058c2",
          "sha256": "8859e15a0ea8655e85c2ab67a7b3d606c56d9d110663907ad0fafa28403e5adb",
          "sha1": "65e03b05eb07e8025434a7917a99e275fb21d139",
          "md5": "fdb3634637f70b58d25fb51ab80dce33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.10.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-undertow",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-servlet",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.4.4.jar",
          "url": "core-spring-boot-1.4.4.jar",
          "size": 18554,
          "sha512": "8724da7e5a9e39d8d002db631eabc9b41f7d0e4fd824f85f716bf7a3a3d57859b468068b509d7f59f52229dfd1140a6e8b2102a31787b529d0560914161058c2",
          "sha256": "8859e15a0ea8655e85c2ab67a7b3d606c56d9d110663907ad0fafa28403e5adb",
          "sha1": "65e03b05eb07e8025434a7917a99e275fb21d139",
          "md5": "fdb3634637f70b58d25fb51ab80dce33"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-spring-boot-1.4.4-sources.jar",
          "url": "core-spring-boot-1.4.4-sources.jar",
          "size": 11565,
          "sha512": "9e42241f24f55b857d7d3ccd251e5dc3a638c13af30349ba8588fe7217b9275af1464483cc77e9d29819dd1f300bd5ac5cc0e655515208dec37d14efe0e1df24",
          "sha256": "36bdc82ff8fbaa66a9e640108d4fbb3d762763d42089f005127a2d310f19517c",
          "sha1": "5b107924b2de8b9a0a52bd11766957850c548bd7",
          "md5": "3c56693411e5d5a4cb1e008476fe5898"
        }
      ]
    }
  ]
}
