{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-spring-boot",
    "version": "1.4.4-1b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.4-1b"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          }
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.4.4-1b.jar",
          "url": "core-spring-boot-1.4.4-1b.jar",
          "size": 18556,
          "sha512": "c897c06f25d4cb4c7d75567e5a12439476b7aad55bbe35200b8a234606c270b6fa768b37744e3f61d67d1ce44eb8a031b020e66103dc7adfafb5a584c86e29a0",
          "sha256": "a9cb70e55f9dabc484f55a33f1335f931351f9d4f3e78acddd9297abb0d831cb",
          "sha1": "85356575aade8ab19b20d25545085a4337249dab",
          "md5": "4d3cec79d1d47bbab7739bfd6b529dc1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.10.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-undertow",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-servlet",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.4-1b"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.4.4-1b.jar",
          "url": "core-spring-boot-1.4.4-1b.jar",
          "size": 18556,
          "sha512": "c897c06f25d4cb4c7d75567e5a12439476b7aad55bbe35200b8a234606c270b6fa768b37744e3f61d67d1ce44eb8a031b020e66103dc7adfafb5a584c86e29a0",
          "sha256": "a9cb70e55f9dabc484f55a33f1335f931351f9d4f3e78acddd9297abb0d831cb",
          "sha1": "85356575aade8ab19b20d25545085a4337249dab",
          "md5": "4d3cec79d1d47bbab7739bfd6b529dc1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-spring-boot-1.4.4-1b-sources.jar",
          "url": "core-spring-boot-1.4.4-1b-sources.jar",
          "size": 11567,
          "sha512": "9706334fa4f1370bbd4fd49fdeae2d90d9ef3c0d9a57675b92972cb7580ee119d6232651927efe66cee1ff3cad19a1a77b95283861f207ecd1013691a5d048d8",
          "sha256": "79c5ad651507f49b047347104a273d4b7b3ecdf4174d9c11d2e84c0502c02b56",
          "sha1": "d3a6d39dd07ac0efe91f424dfed163261077763a",
          "md5": "da6bfa52374be97a0a7100e7771893c2"
        }
      ]
    }
  ]
}
