{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-spring-boot",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          }
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.2.1.jar",
          "url": "core-spring-boot-1.2.1.jar",
          "size": 8748,
          "sha512": "add5aefa0fc024c111cad68dc4bd2cd5f98008765658d6083d90cb9561d680f7956aabddad261aab243b7cb20f7b9a5b6b0f9758d2fdd43531c0eced8f32d3b9",
          "sha256": "e50a6d8b01b1a8f74610411bf198e1b54b5634477881797023128d051f383b22",
          "sha1": "00b369a7c144d9e49168defb9dffaa5ceb8eeef5",
          "md5": "efddeaa723221629581d2bdd30db3031"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.10.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-undertow",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-servlet",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.2.1.jar",
          "url": "core-spring-boot-1.2.1.jar",
          "size": 8748,
          "sha512": "add5aefa0fc024c111cad68dc4bd2cd5f98008765658d6083d90cb9561d680f7956aabddad261aab243b7cb20f7b9a5b6b0f9758d2fdd43531c0eced8f32d3b9",
          "sha256": "e50a6d8b01b1a8f74610411bf198e1b54b5634477881797023128d051f383b22",
          "sha1": "00b369a7c144d9e49168defb9dffaa5ceb8eeef5",
          "md5": "efddeaa723221629581d2bdd30db3031"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-spring-boot-1.2.1-sources.jar",
          "url": "core-spring-boot-1.2.1-sources.jar",
          "size": 5645,
          "sha512": "a97f26828595436639efc2a120c0c22a7977704c2c1391684ace8f4439a909f249efc918a9ee242e8acdcaf083e9e848edd54bf10fee4d5fb0851ec20fed0e4a",
          "sha256": "ac86e1933d68cad77aa98399e48db15dde05bfd4cfdd129c8b51178b1009689a",
          "sha1": "c0405adb5ee2b5c63b29e1079ad8c610896c08b3",
          "md5": "7db5be37b74ae71937438927df7ddfcb"
        }
      ]
    }
  ]
}
