{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-spring-boot",
    "version": "1.4.4-b5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.4-b5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          }
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.4.4-b5.jar",
          "url": "core-spring-boot-1.4.4-b5.jar",
          "size": 18578,
          "sha512": "3b44a2050592e903a33386125310a938e6d952238702c04929869539e4739989fe4f2fbdbaab41a08c4939484bb16d09243735f30743173ea6a44cc43519dfdc",
          "sha256": "b4a23f698438a53d2a59820ba8af5426e6621899c41d75f45dfbcaec8b80d035",
          "sha1": "047985ae3e2f10c5754ad18c651a60f7367162e3",
          "md5": "a89cf7424e63da7271553b12bdf8cf46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.10.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-undertow",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-servlet",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.4-b5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.4.4-b5.jar",
          "url": "core-spring-boot-1.4.4-b5.jar",
          "size": 18578,
          "sha512": "3b44a2050592e903a33386125310a938e6d952238702c04929869539e4739989fe4f2fbdbaab41a08c4939484bb16d09243735f30743173ea6a44cc43519dfdc",
          "sha256": "b4a23f698438a53d2a59820ba8af5426e6621899c41d75f45dfbcaec8b80d035",
          "sha1": "047985ae3e2f10c5754ad18c651a60f7367162e3",
          "md5": "a89cf7424e63da7271553b12bdf8cf46"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-spring-boot-1.4.4-b5-sources.jar",
          "url": "core-spring-boot-1.4.4-b5-sources.jar",
          "size": 11590,
          "sha512": "aee878b0aac919e5254139469f6fc2ef7d8ad70a1d815cedbf49d883a6675733eb57ad1475b85e9311c11006958ad227d397558172901ec858188be80501dcb2",
          "sha256": "ca81314311d4ed9b5b0a626d984ed76d6ce3930f6a69ef5702424dfe7c037361",
          "sha1": "a8c32cdf084ad907a04dd3ce3e77b8a5e194866b",
          "md5": "5cbb54b5c916d422830c72c83f13600f"
        }
      ]
    }
  ]
}
