{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-test",
    "version": "1.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.9.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-inline",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.24.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-test-1.4.2.jar",
          "url": "core-test-1.4.2.jar",
          "size": 17934,
          "sha512": "309ba52ca4e36f32a8c9f19be73fbd28e50ad88a010a8b4c2b87776ec47d76297470a112396d5ca2806ec880103ef4ef3d6e758fdbf82f4522fc0af7fac4a3ec",
          "sha256": "b30d441d9a0fd0a6da57d6389d7f0aeee60d9065a3d26abdde643d42dd4f1827",
          "sha1": "1bf3c9e7f764379cd937c4c24f20ab8e511bef15",
          "md5": "6cc13e68ece34abd3ab0cfe2ce833f5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.9.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.9.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-inline",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.24.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-test-1.4.2.jar",
          "url": "core-test-1.4.2.jar",
          "size": 17934,
          "sha512": "309ba52ca4e36f32a8c9f19be73fbd28e50ad88a010a8b4c2b87776ec47d76297470a112396d5ca2806ec880103ef4ef3d6e758fdbf82f4522fc0af7fac4a3ec",
          "sha256": "b30d441d9a0fd0a6da57d6389d7f0aeee60d9065a3d26abdde643d42dd4f1827",
          "sha1": "1bf3c9e7f764379cd937c4c24f20ab8e511bef15",
          "md5": "6cc13e68ece34abd3ab0cfe2ce833f5c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-test-1.4.2-sources.jar",
          "url": "core-test-1.4.2-sources.jar",
          "size": 9208,
          "sha512": "eda41576811dce268aaae7856fd8832fa668b8469e5bd8e6af558b05c9d7ed609f44185ea679a5a150b14d5307b0cb84406a2ab5789d749493d9fbe4d3204c77",
          "sha256": "2fa0342968e32019c5c48c7c9c56744a42c2c03c470ba1265be28a901ca590e0",
          "sha1": "2b995e0963d73cb83c4b99228c3add862ef9e4e9",
          "md5": "762c1fa3fc1d0e9903a298d98c772b5d"
        }
      ]
    }
  ]
}
