{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-api",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-api-1.3.0.jar",
          "url": "core-api-1.3.0.jar",
          "size": 7750,
          "sha512": "8cc6bcf714c6380da556c9cf7ef4ac4a87b29b0bd273d26dd4cedba7e035c275b390b34a8441207c8c7ce58f6f36816de1a01c175b3bf35b2fc326cddadc4b38",
          "sha256": "bcb9d97667a0bd10b20aee8643c508e8101153815f804cceaa58d71ae2c9f847",
          "sha1": "c8a12f867786c99abe085097521c210e3eb76c5f",
          "md5": "028c8b80ef91d102f4591dbaa7072df6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-api-1.3.0.jar",
          "url": "core-api-1.3.0.jar",
          "size": 7750,
          "sha512": "8cc6bcf714c6380da556c9cf7ef4ac4a87b29b0bd273d26dd4cedba7e035c275b390b34a8441207c8c7ce58f6f36816de1a01c175b3bf35b2fc326cddadc4b38",
          "sha256": "bcb9d97667a0bd10b20aee8643c508e8101153815f804cceaa58d71ae2c9f847",
          "sha1": "c8a12f867786c99abe085097521c210e3eb76c5f",
          "md5": "028c8b80ef91d102f4591dbaa7072df6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-api-1.3.0-sources.jar",
          "url": "core-api-1.3.0-sources.jar",
          "size": 6053,
          "sha512": "2329a15f22e231564fa2ed32596d1160608ebd9e6a967afd622553811ffa6c954a759e6e266956c32173d6e1e36a452823a5dc639f9cc76066c2e3dbbe26c488",
          "sha256": "527c2eb08206ce434e4ba7235b4046e1b7d9f9c3a3f148c849cc28ea2226ea25",
          "sha1": "36aa319b915929db768adff75a7c033cca6bfd42",
          "md5": "7f610ec8db1c0220c1120d85e857d66a"
        }
      ]
    }
  ]
}
