{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-spring-boot",
    "version": "1.4.4-b4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.4-b4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          }
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.4.4-b4.jar",
          "url": "core-spring-boot-1.4.4-b4.jar",
          "size": 18556,
          "sha512": "05d825af353ac518b42f9d6cd2c3c2e31946bdc8657d524344e62ce08d56d88e7e50ecfa233552327e4abf89b5958b34f7683d7bf39615a64477e035e8d52c9f",
          "sha256": "212a008e55b2d7b9ce5b18953ff318152c8672d5218940a9a91aa92aac70de15",
          "sha1": "46dd90ec2635af2860a346a8b61e95536b3b4288",
          "md5": "20d5d809579c75bca3a068cddf241c8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.10.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-undertow",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-servlet",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.4-b4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.4.4-b4.jar",
          "url": "core-spring-boot-1.4.4-b4.jar",
          "size": 18556,
          "sha512": "05d825af353ac518b42f9d6cd2c3c2e31946bdc8657d524344e62ce08d56d88e7e50ecfa233552327e4abf89b5958b34f7683d7bf39615a64477e035e8d52c9f",
          "sha256": "212a008e55b2d7b9ce5b18953ff318152c8672d5218940a9a91aa92aac70de15",
          "sha1": "46dd90ec2635af2860a346a8b61e95536b3b4288",
          "md5": "20d5d809579c75bca3a068cddf241c8f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-spring-boot-1.4.4-b4-sources.jar",
          "url": "core-spring-boot-1.4.4-b4-sources.jar",
          "size": 11567,
          "sha512": "38692c8a77b132f9ad4763a4c111b99a4cf10313efd92efb434c4a64dfeb6a07f0a83434e1dc42b68ece137f5b2d94cdaa3d3221940d0f8aa07d7497b779f53b",
          "sha256": "e08d54ab3f549f561e400bca80b42a7556d7d6cc6150636d84272e5514fc4230",
          "sha1": "4ca8b812ff4cab8999fdb5c2d5e313d8cbe98518",
          "md5": "60e6122b1239df79a9f6575a4c661b5f"
        }
      ]
    }
  ]
}
