{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.3.0.jar",
          "url": "core-1.3.0.jar",
          "size": 399761,
          "sha512": "2d53ec0c84fb2d28a7e12f7186db6da53e9397d3a483835daf8d627e686826c8cf523bfce18bb153d918b88e62a99e11f25d1052ea1c6cf2f6bff0bb5fc6b3b2",
          "sha256": "0c47b3faa64b6b6b30c5af273dfa35459c77346e94d49fb2fc076aeabbc9ff27",
          "sha1": "f4c8beba21604023d94daed4dd3cde97c120cd6d",
          "md5": "6f5f84893d6061555fb6c5d74ec0c5c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.1-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.10.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.10.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.24.Final"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.8.4"
          }
        },
        {
          "group": "core.framework",
          "module": "core-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.3.0.jar",
          "url": "core-1.3.0.jar",
          "size": 399761,
          "sha512": "2d53ec0c84fb2d28a7e12f7186db6da53e9397d3a483835daf8d627e686826c8cf523bfce18bb153d918b88e62a99e11f25d1052ea1c6cf2f6bff0bb5fc6b3b2",
          "sha256": "0c47b3faa64b6b6b30c5af273dfa35459c77346e94d49fb2fc076aeabbc9ff27",
          "sha1": "f4c8beba21604023d94daed4dd3cde97c120cd6d",
          "md5": "6f5f84893d6061555fb6c5d74ec0c5c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.3.0-sources.jar",
          "url": "core-1.3.0-sources.jar",
          "size": 222734,
          "sha512": "bc6f2cbe4cbfe652711e359dc081736986fb22ade99549de88d6dd990ce277ef9d262c7c5be1310f4dd635377cc45de6076ed8a97b10ea60483aa6c79ab253b3",
          "sha256": "554aeae4cdb84a5a8b104073cdcd83c67a6cac7f8028ff058cdb395f46da6078",
          "sha1": "4dc26d08d2934098328a13bd588087c7bea3c2de",
          "md5": "4bd67f518e10b61b6fc11a2d23fabf93"
        }
      ]
    }
  ]
}
