{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-api",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-api-1.2.3.jar",
          "url": "core-api-1.2.3.jar",
          "size": 7751,
          "sha512": "39b275e5e5570acca3ed67ec493ae88f5564391e448f611a45a9196398797358ab936fba803819a24d940a30793c7e864ef5d6ffa7830218bfc6c652bf2c89ff",
          "sha256": "69f8d048ae18700843f2d14bb343a26c4e75fb77d614e26e809f0669f7e4f443",
          "sha1": "6b13114a908067b7d83dfc3b6e56faa5b858fbdd",
          "md5": "a1936e3c52bed69155c148c252b72b72"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-api-1.2.3.jar",
          "url": "core-api-1.2.3.jar",
          "size": 7751,
          "sha512": "39b275e5e5570acca3ed67ec493ae88f5564391e448f611a45a9196398797358ab936fba803819a24d940a30793c7e864ef5d6ffa7830218bfc6c652bf2c89ff",
          "sha256": "69f8d048ae18700843f2d14bb343a26c4e75fb77d614e26e809f0669f7e4f443",
          "sha1": "6b13114a908067b7d83dfc3b6e56faa5b858fbdd",
          "md5": "a1936e3c52bed69155c148c252b72b72"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-api-1.2.3-sources.jar",
          "url": "core-api-1.2.3-sources.jar",
          "size": 6054,
          "sha512": "309f819e712053113b8e0598c2fc9f56eb283e0294cfb1f01ebb4fe832033d3a0f7f16dae0bf0574a089b1a5be5a5a0aef8ecaf564653d34d33d412c17fc6c4d",
          "sha256": "4371bc036d8b0fadc71072730be8fbed4c74007bdde5a0fcf38362645edc51fe",
          "sha1": "087632dca32ca2dcd733a684ff1362fe388330a8",
          "md5": "2894feb75bb1ea4e381af5a7a2e38c21"
        }
      ]
    }
  ]
}
