{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-test",
    "version": "1.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.9.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-inline",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.24.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-test-1.4.3.jar",
          "url": "core-test-1.4.3.jar",
          "size": 17931,
          "sha512": "e773aa76a931deccc4840c03c7e598288689662f41005b33e134cd5970be1bca0eee2e2daa51d7f653e84c1ae2697c78a2a4ce03ff9e1e4c30efdea8babe0d37",
          "sha256": "a2765a49f1cc201e471b6cc223e3a164f41fdc826c78a18a6e398fa52eb380d0",
          "sha1": "aefd269c1586d944503a24c54dfc9bd9a235e407",
          "md5": "2a801bc0556916a4b93e4afa82126a78"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.9.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.9.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-inline",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.24.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-test-1.4.3.jar",
          "url": "core-test-1.4.3.jar",
          "size": 17931,
          "sha512": "e773aa76a931deccc4840c03c7e598288689662f41005b33e134cd5970be1bca0eee2e2daa51d7f653e84c1ae2697c78a2a4ce03ff9e1e4c30efdea8babe0d37",
          "sha256": "a2765a49f1cc201e471b6cc223e3a164f41fdc826c78a18a6e398fa52eb380d0",
          "sha1": "aefd269c1586d944503a24c54dfc9bd9a235e407",
          "md5": "2a801bc0556916a4b93e4afa82126a78"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-test-1.4.3-sources.jar",
          "url": "core-test-1.4.3-sources.jar",
          "size": 9205,
          "sha512": "423886ccba015fbd22469a336bdc29b13e32bf4b23ac74a7bc581977cfa6e9b1395ea2e1d458ccccd66c27e041a72defcb9fd3d5a87e8379012d40fdec4da0a6",
          "sha256": "7ddb4145d653bf02274cd276cf4fec905609e010cff977b9e0a1c78535df499d",
          "sha1": "9f7e64a3e4fa55bbb6188d8853765756c7f648de",
          "md5": "28c82691de0cf119b017fbde6a044de4"
        }
      ]
    }
  ]
}
