{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-spring-boot",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          }
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.2.0.jar",
          "url": "core-spring-boot-1.2.0.jar",
          "size": 8749,
          "sha512": "d2a320d51a614d0f15c315058f4f5e78ec53c854d98ce0125be91bef408f17eb5443e8345714dc0e113438c98909dafc7ba9039b9464eaea1e24ca3ec4f676b9",
          "sha256": "2500c66c5654c9bd592dc651a56515fdf9bca11ccfca97ef1088424e75abfdbb",
          "sha1": "ae957252e46ab5e8325b7272eac9b30e990c2b88",
          "md5": "287cff9e8fafa6e336a36efc16d75a55"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.10.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-undertow",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-servlet",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.2.0.jar",
          "url": "core-spring-boot-1.2.0.jar",
          "size": 8749,
          "sha512": "d2a320d51a614d0f15c315058f4f5e78ec53c854d98ce0125be91bef408f17eb5443e8345714dc0e113438c98909dafc7ba9039b9464eaea1e24ca3ec4f676b9",
          "sha256": "2500c66c5654c9bd592dc651a56515fdf9bca11ccfca97ef1088424e75abfdbb",
          "sha1": "ae957252e46ab5e8325b7272eac9b30e990c2b88",
          "md5": "287cff9e8fafa6e336a36efc16d75a55"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-spring-boot-1.2.0-sources.jar",
          "url": "core-spring-boot-1.2.0-sources.jar",
          "size": 5646,
          "sha512": "26c2fe48d24b4255128ec179d6fa5ab8ac45e7585772f6b1051ed8ac24536760de35871f0ff9149329fb96c541e2541dbe854f4daf46c32a50c1119c9f9ba34e",
          "sha256": "0d00ae6a559e6dd883c93a9e3defdd7aa0860c941cc1c9d55dd1faf047b4b3e7",
          "sha1": "26330ffdc8d8765e3117e60988c70c33406631ed",
          "md5": "d9517c8a8493d3389316f1e6dc686509"
        }
      ]
    }
  ]
}
