{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-spring-boot",
    "version": "1.4.3-b3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.3-b3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          }
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.4.3-b3.jar",
          "url": "core-spring-boot-1.4.3-b3.jar",
          "size": 18556,
          "sha512": "2fb518bb7e95e7f97f808e92672027539c8c7614f553c7bff7689fa941b0583339d12cbb9d588d18383e56ae9023e70118a94a86877f297d87e46e19ba84e220",
          "sha256": "b030aef34a51d7d5dd9032cfd3bf40c82d0e696f0a4804e21a278d66bec53a1b",
          "sha1": "288347b4478fd1929a708716f4a22f8d96f614d1",
          "md5": "f0a488d20a3be3d96c24b262d0321ce1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.10.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-undertow",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-servlet",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.3-b3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.4.3-b3.jar",
          "url": "core-spring-boot-1.4.3-b3.jar",
          "size": 18556,
          "sha512": "2fb518bb7e95e7f97f808e92672027539c8c7614f553c7bff7689fa941b0583339d12cbb9d588d18383e56ae9023e70118a94a86877f297d87e46e19ba84e220",
          "sha256": "b030aef34a51d7d5dd9032cfd3bf40c82d0e696f0a4804e21a278d66bec53a1b",
          "sha1": "288347b4478fd1929a708716f4a22f8d96f614d1",
          "md5": "f0a488d20a3be3d96c24b262d0321ce1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-spring-boot-1.4.3-b3-sources.jar",
          "url": "core-spring-boot-1.4.3-b3-sources.jar",
          "size": 11567,
          "sha512": "00219b147d7b9f2dae336277a31e40615bb357edf329e0fcd419c21206030412f52ab33cddf69852e869884865cd463a5240a557e29ee2ede9c98df596d840ab",
          "sha256": "3f0009ca7252cafc453698e656ee0f422a7f356a8a084fc0b3b64873aeba3113",
          "sha1": "520e5600e7b30c159f4a699b8b96c1cdee6e3bd1",
          "md5": "990244efe2ce85fbf1be0aab9c04cae0"
        }
      ]
    }
  ]
}
