{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-spring-boot",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          }
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.4.0.jar",
          "url": "core-spring-boot-1.4.0.jar",
          "size": 18137,
          "sha512": "5b2d113c50f2e293a3819c97566672d08de59dfb8d99173d1227adf2bf4e349b256f2998ca90f4a887e36888a9019f43136f24bdfeaa3adb38f213429d4a0a2d",
          "sha256": "3d1ed98859b2195fb8f83c15785c9477c2a34fc5d2ae5186a71c1ccede07cf94",
          "sha1": "42a0913e7195a3a49233cb78dddbedd087e76c8f",
          "md5": "f94e43ef201a35b86d908d678dc1c450"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.10.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-undertow",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-servlet",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.4.0.jar",
          "url": "core-spring-boot-1.4.0.jar",
          "size": 18137,
          "sha512": "5b2d113c50f2e293a3819c97566672d08de59dfb8d99173d1227adf2bf4e349b256f2998ca90f4a887e36888a9019f43136f24bdfeaa3adb38f213429d4a0a2d",
          "sha256": "3d1ed98859b2195fb8f83c15785c9477c2a34fc5d2ae5186a71c1ccede07cf94",
          "sha1": "42a0913e7195a3a49233cb78dddbedd087e76c8f",
          "md5": "f94e43ef201a35b86d908d678dc1c450"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-spring-boot-1.4.0-sources.jar",
          "url": "core-spring-boot-1.4.0-sources.jar",
          "size": 11462,
          "sha512": "8f947f87554365a0807e82e120fe4eb59f26c6f8d5ff1560237fc012ad81b5dd8a7996f8e1e874b71c26fabe36525bd2be7c42dd60c9e127306b92fa2abe428b",
          "sha256": "2ff0de3f738ae6097576609456f4f4b7e8146fbb0f5635174e27ee1e896f4bc2",
          "sha1": "b606b1edb2f83963de3cc79d0b9e4263df35390c",
          "md5": "81bb136a94a4a224ba825ce557737405"
        }
      ]
    }
  ]
}
