{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-spring-boot",
    "version": "1.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          }
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.4.3.jar",
          "url": "core-spring-boot-1.4.3.jar",
          "size": 18549,
          "sha512": "99b091d017b24538e807ec6846c7cfc7efd0cfab003a0a5641e6c5e6ddd591598d9f647d0902c803bf6de5bf6acd6d540ed115609bdb6519e760288772e5dca8",
          "sha256": "5d78097c41939edd0c97f33ccaff12f6ebd33bc3a5fa0063a4dfa2f1105f443a",
          "sha1": "054327219a1ca37cfc0dca0e37b2c1b05cd4a5dc",
          "md5": "a79a59c27d2be61c55e0133065b354d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.10.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-undertow",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-servlet",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.4.3.jar",
          "url": "core-spring-boot-1.4.3.jar",
          "size": 18549,
          "sha512": "99b091d017b24538e807ec6846c7cfc7efd0cfab003a0a5641e6c5e6ddd591598d9f647d0902c803bf6de5bf6acd6d540ed115609bdb6519e760288772e5dca8",
          "sha256": "5d78097c41939edd0c97f33ccaff12f6ebd33bc3a5fa0063a4dfa2f1105f443a",
          "sha1": "054327219a1ca37cfc0dca0e37b2c1b05cd4a5dc",
          "md5": "a79a59c27d2be61c55e0133065b354d6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-spring-boot-1.4.3-sources.jar",
          "url": "core-spring-boot-1.4.3-sources.jar",
          "size": 11560,
          "sha512": "7d107314e7f3f3733b94198a5076fd798e7eeee4795ab8031f98d9dda1f6c6ed16279458fb4de07b6dcf8ca471375da3725640a2a70cc456f8cb1af507a5e183",
          "sha256": "fb02334622d75cfa58c0741fe5d3e2196441834d5ec4efe4f9d94b35d222bb20",
          "sha1": "657496aff933ca548d75aefc16aee1beccc2b87c",
          "md5": "4080d7ee987dd7c09d90bfd40e755544"
        }
      ]
    }
  ]
}
