{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-spring-boot",
    "version": "1.4.3-b4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.3-b4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          }
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.4.3-b4.jar",
          "url": "core-spring-boot-1.4.3-b4.jar",
          "size": 18556,
          "sha512": "5e7b92325bcea15929a6b4158fa73b50cfb7c564389031c73dc1f96c315c899d7c04d9a1955a4dbefdc36723b5fc55aa553e00d8e340153588b77f38bd9ff97f",
          "sha256": "f3a3b014d75cfb0426e2319f79878f3effbd85e6515b3198408bd7299bf70f83",
          "sha1": "e73efbe14ea10de9434d831cbda2f3166a9f320c",
          "md5": "54a273b12c7ab26a985a680651aee451"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.10.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-undertow",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-servlet",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.3-b4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.4.3-b4.jar",
          "url": "core-spring-boot-1.4.3-b4.jar",
          "size": 18556,
          "sha512": "5e7b92325bcea15929a6b4158fa73b50cfb7c564389031c73dc1f96c315c899d7c04d9a1955a4dbefdc36723b5fc55aa553e00d8e340153588b77f38bd9ff97f",
          "sha256": "f3a3b014d75cfb0426e2319f79878f3effbd85e6515b3198408bd7299bf70f83",
          "sha1": "e73efbe14ea10de9434d831cbda2f3166a9f320c",
          "md5": "54a273b12c7ab26a985a680651aee451"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-spring-boot-1.4.3-b4-sources.jar",
          "url": "core-spring-boot-1.4.3-b4-sources.jar",
          "size": 11567,
          "sha512": "d8a9cd4aa423f0368c40d1b754081d49eb86a125e3fc338273e76cbdc62ddc524db3940c5022041508c5b1e1751b8025807493e0a798cea10b28a38d8e26dbfd",
          "sha256": "d95f915f7cb4e8aee6a787a9ce6f0b66c7a6d5f37e24e481d8f4a2f386e2c370",
          "sha1": "b87f3eb0369314a9eae3b11019450f94b231c616",
          "md5": "229ce938d8473fd04047be945e97e429"
        }
      ]
    }
  ]
}
