{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-spring-boot",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          }
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.3.0.jar",
          "url": "core-spring-boot-1.3.0.jar",
          "size": 17944,
          "sha512": "5f92a0168c1bdb85e66c5ec3773df8e22fa19dfc7c17ddb39d6500cc8769b83216bce59be2c41344a62207fe70606d086ccfd550411d1dc288463de9f3838961",
          "sha256": "a1708443573786c601a49f19ee8cc9c1a1e4909f43a0ae46e7c03570a1a1483c",
          "sha1": "c104bc0494922c14689627d7c5a1a54696a3de5e",
          "md5": "2c9fcc0503926122f6c13ce567961c03"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.10.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-undertow",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-servlet",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.3.0.jar",
          "url": "core-spring-boot-1.3.0.jar",
          "size": 17944,
          "sha512": "5f92a0168c1bdb85e66c5ec3773df8e22fa19dfc7c17ddb39d6500cc8769b83216bce59be2c41344a62207fe70606d086ccfd550411d1dc288463de9f3838961",
          "sha256": "a1708443573786c601a49f19ee8cc9c1a1e4909f43a0ae46e7c03570a1a1483c",
          "sha1": "c104bc0494922c14689627d7c5a1a54696a3de5e",
          "md5": "2c9fcc0503926122f6c13ce567961c03"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-spring-boot-1.3.0-sources.jar",
          "url": "core-spring-boot-1.3.0-sources.jar",
          "size": 11383,
          "sha512": "92ca9c274f1366398673168cc1a5ee5625e81fb3117cdf3ea99ff02c560c31fe6df95f30b7db658241d0cb0f6e20ba99d38337459d06cba03f998247adf6db9d",
          "sha256": "aa979a553c94f7e751ee2cfd67e90d7e719b45c3f33aa23b9bca0af2049b1707",
          "sha1": "5d2a298bf734a5429f87dddff5c727d45eee2307",
          "md5": "5822def38ea4f40d820cd0bf595842b7"
        }
      ]
    }
  ]
}
