{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-spring-boot",
    "version": "1.4.4-b8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.4-b8"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          }
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.4.4-b8.jar",
          "url": "core-spring-boot-1.4.4-b8.jar",
          "size": 18573,
          "sha512": "a1ea6dc9d5f33cb8dce88370aba3a8fcee35840867cbe51a9bf125226c031e6dd3515d5191ce91939cc7a5a48532842e28f9346544a144a51e9dd61fd88249e8",
          "sha256": "424adca48128b7acc537a2bd04dc5e3236fdbc98c9dd62964ca3303f70ef1758",
          "sha1": "13c956bbae8bbebb0526182e3a58bd797954a122",
          "md5": "bdd518430c3ec1dd0dab95eed0c093de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.10.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-undertow",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-servlet",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "4.3.12.RELEASE"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "4.3.12.RELEASE"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.4-b8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.4.4-b8.jar",
          "url": "core-spring-boot-1.4.4-b8.jar",
          "size": 18573,
          "sha512": "a1ea6dc9d5f33cb8dce88370aba3a8fcee35840867cbe51a9bf125226c031e6dd3515d5191ce91939cc7a5a48532842e28f9346544a144a51e9dd61fd88249e8",
          "sha256": "424adca48128b7acc537a2bd04dc5e3236fdbc98c9dd62964ca3303f70ef1758",
          "sha1": "13c956bbae8bbebb0526182e3a58bd797954a122",
          "md5": "bdd518430c3ec1dd0dab95eed0c093de"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-spring-boot-1.4.4-b8-sources.jar",
          "url": "core-spring-boot-1.4.4-b8-sources.jar",
          "size": 11585,
          "sha512": "8b1b1ff10069997bf5429096f26b48dc9390c36d94f23fa5b7dd8e0f7f1adfbff568e2c37f5a3dfd1fe0bcd068a89093b14ff4d6ed8aed9a1b9bb3921b676700",
          "sha256": "3a08b6e72d91dcd923d2eed0f933943bb57568458e707f66b56ec47165b7a903",
          "sha1": "7c97112700841dc7eba945eb5271ba9db4ca5c9f",
          "md5": "1d9bd9e383e1c50e95b8d05a0cd8cc44"
        }
      ]
    }
  ]
}
