{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-spring-boot",
    "version": "1.4.3-b2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.3-b2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          }
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.4.3-b2.jar",
          "url": "core-spring-boot-1.4.3-b2.jar",
          "size": 18556,
          "sha512": "1aa19333ab474e87972e295618cbe1c1ef01d744032a90d6d900bf85abed48054f168e5fefa653c5cd6c97dc04fc72645fbc42ca845d8032f1e62394d1cfc70f",
          "sha256": "11daedc708da24062e39bd0bc1a37ba5512cb29d9955bc98af1a1f43d65f17b8",
          "sha1": "72710f9af0fdd9815ec0b18266fac0f39f70cddb",
          "md5": "749e26ea842127304e0be07cba9561e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.10.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-undertow",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-servlet",
          "version": {
            "requires": "2.2.24.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core",
          "version": {
            "requires": "1.4.3-b2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.7.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "spring-boot-starter-logging"
            },
            {
              "group": "*",
              "module": "spring-boot-starter-tomcat"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-spring-boot-1.4.3-b2.jar",
          "url": "core-spring-boot-1.4.3-b2.jar",
          "size": 18556,
          "sha512": "1aa19333ab474e87972e295618cbe1c1ef01d744032a90d6d900bf85abed48054f168e5fefa653c5cd6c97dc04fc72645fbc42ca845d8032f1e62394d1cfc70f",
          "sha256": "11daedc708da24062e39bd0bc1a37ba5512cb29d9955bc98af1a1f43d65f17b8",
          "sha1": "72710f9af0fdd9815ec0b18266fac0f39f70cddb",
          "md5": "749e26ea842127304e0be07cba9561e4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-spring-boot-1.4.3-b2-sources.jar",
          "url": "core-spring-boot-1.4.3-b2-sources.jar",
          "size": 11567,
          "sha512": "ad29d61f5b1f39d83a820984846d12d3df395e7a6a95d79d0c29990b027e501952ed20cb980babd591777dc2f26feaf76da9d85b5e00b90fe9f2a1ae133749c0",
          "sha256": "e72114547e95175cb4058af95091a5a639773e22d96aed4e64aa749253e396a1",
          "sha1": "3d74838b3e221240014492ce8be147af0c9d3b07",
          "md5": "6e57fa20639d4ab9e0c4362210e9d938"
        }
      ]
    }
  ]
}
